vonk: releasenotes version 4.2.0
FirelyTeam/firely-docs pull request #186
Opened 2021-06-02 16:19 UTC by cknaap

2021-06-02 16:48 UTC, alexzautke requested changes

2021-06-02 16:48 UTC, alexzautke commented on firelyserver/releasenotes/releasenotes.rst
> +#. POSTing an empty (Patient) resource returned an error.
Issue was closed as won’t do

2021-06-03 06:41 UTC, cknaap commented on firelyserver/releasenotes/releasenotes.rst
> +#. POSTing an empty (Patient) resource returned an error.
Sharp!

2021-06-03 06:42 UTC, merged

2021-06-03 06:43 UTC, cknaap commented
@alexzautke : merged it without re-review as you were on holiday :-)